'use strict';
var util = require('util');
var XsODataError = require('./xsODataError');

module.exports = InternalError;

/**
 * Error indicating an XSOData internal problem, e.g. used in try/catch statements to catch runtime errors
 * @param message
 * @param cause
 * @param context
 * @constructor
 */
function InternalError(message, context, cause) {
    XsODataError.call(this, message || 'InternalError', cause);
    this.context = context;
    if (cause && cause.stack && context && context.logger) {
        context.logger.error('InternalError', cause.stack);
    }
}

util.inherits(InternalError, XsODataError);
